[versions]
androidXExtJunit = "1.1.3"
androidXEspressoCore = "3.4.0"

[libraries]
androidXExtJunit = { module = "androidx.test.ext:junit", version.ref = "androidXExtJunit" }
androidXEspressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "androidXEspressoCore" }

[plugins]

[bundles]
androidTestBundle = ["androidXExtJunit", "androidXEspressoCore"]