[versions]
androidXEspressoCore = "3.5.0"
androidXExtJunit = "1.1.4"

[libraries]
androidXEspressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "androidXEspressoCore" }
androidXExtJunit = { module = "androidx.test.ext:junit", version.ref = "androidXExtJunit" }

[bundles]
androidTestBundle = [
    "androidXEspressoCore",
    "androidXExtJunit",
]
