[versions]
# Top level dependencies
androidToolsBuildGradle = "7.3.1"
androidXAppCompat = "1.5.1"
androidXConstraintLayout = "2.1.4"
#Module level dependencies
androidXCoreKtx = "1.9.0"
androidXDatastore = "1.0.0"
androidXLifecycle = "2.5.1"
androidXNavigation = "2.5.3"
firebaseAnalytics = "21.2.0"
firebaseCrashlytics = "18.3.1"
firebaseGradle = "2.9.2"
glide = "4.14.2"
googleMaterial = "1.7.0"
googleServices = "4.3.14"
koin = "3.2.2"
kotlinGradlePlugin = "1.7.21"
kotlinXCoroutines = "1.6.4"
ksp = "1.7.21-1.0.8"
moshi = "1.14.0"
okhttp = "4.9.3"
retrofit = "2.9.0"
room = "2.4.3"
timber = "5.0.1"

[libraries]
# Top level dependencies
androidToolsBuildGradle = { module = "com.android.tools.build:gradle", version.ref = "androidToolsBuildGradle" }
androidXAppCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidXAppCompat" }
androidXConstraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidXConstraintLayout" }
# Module level dependencies
androidXCoreKtx = { module = "androidx.core:core-ktx", version.ref = "androidXCoreKtx" }
androidXDatastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidXDatastore" }
androidXLifecycleCommon = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidXLifecycle" }
androidXLifecycleLiveData = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidXLifecycle" }
androidXLifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidXLifecycle" }
androidXNavigationFragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidXNavigation" }
androidXNavigationUI = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidXNavigation" }
firebaseAnalytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebaseAnalytics" }
firebaseCrashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebaseGradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseGradle" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
googleMaterial = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
googleServices = { module = "com.google.gms:google-services", version.ref = "googleServices" }
koinAndroid = "io.insert-koin:koin-android:3.3.0"
koinCore = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlinXCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinXCoroutines" }
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshiKsp = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
navigationSafeArgs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidXNavigation" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitMoshiConverter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
roomKsp = { module = "androidx.room:room-compiler", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[bundles]
androidXLifecycleBundle = [
    "androidXLifecycleCommon",
    "androidXLifecycleLiveData",
    "androidXLifecycleViewModel",
]
androidXNavigationBundle = [
    "androidXNavigationFragment",
    "androidXNavigationUI",
]
koinBundle = [
    "koinAndroid",
    "koinCore",
]
okhttpBundle = [
    "okhttp",
    "okhttpInterceptor",
]
retrofitBundle = [
    "retrofit",
    "retrofitMoshiConverter",
]
roomBundle = [
    "roomKtx",
    "roomRuntime",
]

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
