[versions]
#Module level dependencies
androidXCoreKtx = "1.7.0"
androidXAppCompat = "1.4.1"
androidXConstraintLayout = "2.1.3"
androidXLifecycle = "2.4.1"
androidXNavigation = "2.4.1"
androidXDatastore = "1.0.0"

googleMaterial = "1.5.0"

kotlinXCoroutines = "1.6.0"

okhttp = "4.9.3"
koin = "3.1.5"
retrofit = "2.9.0"
moshi = "1.13.0"
glide = "4.13.0"
timber = "5.0.1"

# Top level dependencies
androidToolsBuildGradle = "7.1.2"
kotlinGradlePlugin = "1.6.10"

[libraries]
# Module level dependencies
androidXCoreKtx = { module = "androidx.core:core-ktx", version.ref = "androidXCoreKtx" }
androidXAppCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidXAppCompat" }
androidXConstraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidXConstraintLayout" }
androidXLifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidXLifecycle" }
androidXLifecycleLiveData = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidXLifecycle" }
androidXLifecycleCommon = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidXLifecycle" }
androidXNavigationFragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidXNavigation" }
androidXNavigationUI = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidXNavigation" }
androidXDatastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidXDatastore" }

googleMaterial = { module = "com.google.android.material:material", version.ref = "googleMaterial" }

kotlinXCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinXCoroutines" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

koinCore = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koinAndroid = { module = "io.insert-koin:koin-android", version.ref = "koin" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitMoshiConverter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshiKapt = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideKapt = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Top level dependencies
androidToolsBuildGradle = { module = "com.android.tools.build:gradle", version.ref = "androidToolsBuildGradle" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
navigationSafeArgs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidXNavigation" }

[bundles]
androidXLifecycleBundle = ["androidXLifecycleViewModel", "androidXLifecycleLiveData", "androidXLifecycleCommon"]
androidXNavigationBundle = ["androidXNavigationFragment", "androidXNavigationUI"]
okhttpBundle = ["okhttp", "okhttpInterceptor"]
koinBundle = ["koinCore", "koinAndroid"]
retrofitBundle = ["retrofit", "retrofitMoshiConverter"]