[versions]
junit = "4.13.2"
mockWebServer = "4.10.0"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
mockWebServer = {module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockWebServer" }

[bundles]
testBundle = [
    "junit",
]
