[versions]
junit = "4.13.2"
mockWebServer = "4.10.0"
kotlinX = "1.6.4"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
mockWebServer = {module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockWebServer" }
kotlinXCoroutines = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinX"}

[bundles]
testBundle = [
    "junit",
]
